### ISSUE TITLE
Support authentication via CloudSQL Proxy

### ISSUE THREAD

**Issue by hsharrison** [crossplane-contrib/provider-sql#101]
### What problem are you facing?
We'd like to connect to a CloudSQL instance by connection string rather than endpoint.

Specifically, we always use [Cloud SQL Proxy](https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine#proxy) to connect from GKE, so it would be great if that pattern could be supported here.

### How could Crossplane help solve your problem?
Support passing a connection string to provider-sql, in which case launch a CloudSQL Proxy sidecar to provide authentication.

**Comment by Duologic** [comment]
It is possible to pass along the connection string when using Compositions.

**Comment by Duologic** [comment]
As said last time, this can be solved with a Composition.
