### ISSUE TITLE
provider can't connect to database if password contains special characters

### ISSUE THREAD

**Issue by mateusz-lubanski-sinch** [crossplane-contrib/provider-sql#121]
### What happened?
When kubernetes Secret pointed by `mysql.sql.crossplane.io/v1alpha1/ProviderConfig`.spec.credentials.connectionSecretRef ` parameter contain special characters in password (e.g. `}` or `!`) than sql provider can't connect to RDS Instance

`mysql.sql.crossplane.io/v1alpha1/databases` and  `mysql.sql.crossplane.io/v1alpha1/users`  throws 
```
Warning  CannotObserveExternalResource  16m (x242 over 2d3h)  managed/database.mysql.sql.crossplane.io  cannot select database: Error 1045: Access denied for user 'root'@'100.64.44.98' (using password: YES)
```

### What environment did it happen in?
AWS EKS
RDS Instance with mysql engine

### Expected behaviour: 
provider-sql is able to connecto to AWS RDS Instance when password contains special characters

**Comment by chlunde** [comment]
Which version is this? I believe it was fixed by https://github.com/crossplane-contrib/provider-sql/pull/108

**Comment by mateusz-lubanski-sinch** [comment]
@chlunde I used `v0.5.0`, seems that at the time when I was running my tests you provided a fix
I just tested `v0.6.0` and it works seamlessly so we can close this ticket! 

Thanks @chlunde <3

**Comment by mateusz-lubanski-sinch** [comment]
duplicates https://github.com/crossplane-contrib/provider-sql/issues/98
