### ISSUE TITLE
Revoke all when updating grants might be replaced by a grants diff

### ISSUE THREAD

**Issue by alereca** [crossplane-contrib/provider-sql#126]
### What problem are you facing?

In mysql grant controller, all grants are revoked before assigning the new ones, as stated in the comment that might leave applications with no access to the DB for a short time
```go
        // Remove current grants since it's not possible to update grants.
	// This might leave applications with no access to the DB for a short time
	// until the privileges are granted again.
	// Using a transaction is unfortunately not possible because a GRANT triggers
	// an implicit commit: https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html
	query := fmt.Sprintf("REVOKE ALL ON %s.%s FROM %s@%s",
		dbname,
		table,
		mysql.QuoteValue(username),
		mysql.QuoteValue(host),
	)
```
https://github.com/crossplane-contrib/provider-sql/blob/master/pkg/controller/mysql/grant/reconciler.go#L279

### How could Crossplane help solve your problem?

What about making a comparison between current mysql grants for that user-table and then revoking the ones that are no longer required `privileges to revoke = observed privileges - requested privileges`? As well as granting the ones that are required now  `privileges to grant = requested privileges - observed privileges`

![image](https://user-images.githubusercontent.com/41701343/215150923-c59ed08d-691e-4777-ad2b-a2d63b7b171d.png)

I understand that observed privileges list cannot be passed from observed method to update method, since `managed.ExternalObservation{}` struct does not have a field for that. So this will involve an additional query to database in the update method.

I would like to work in a pr if this feature is considered as desirable

**Comment by alereca** [comment]
Similar to what has been done for mssql https://github.com/crossplane-contrib/provider-sql/blob/master/pkg/controller/mssql/grant/reconciler.go#L177

**Comment by Duologic** [comment]
I'm running into alternative issues with `REVOKE ALL` and think this might help improve the situation.

**Comment by luis-alen** [comment]
This patch was included on 0.7.0 (https://github.com/crossplane-contrib/provider-sql/releases/tag/v0.7.0), but it doesn't seem to fix the issue.

I still face it after upgrading. Below is what I see on mysql general logs and when `my-app` tries to run a query in between REVOKE and GRANT, it of course gets a permission denied error:

```
2023-11-07T11:04:33.937835Z     1673736 Query   SHOW GRANTS FOR 'my-app'@'%'
2023-11-07T11:04:33.945302Z     1673738 Query   REVOKE ALL ON `my-app`.* FROM 'my-app'@'%'
2023-11-07T11:04:33.967178Z     1673740 Query   GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, REFERENCES, SELECT, SHOW VIEW, TRIGGER, UPDATE ON `my-app`.* TO 'my-app'@'%'
```

**Comment by Duologic** [comment]
It looks like the `REVOKE ALL` query is a case of going from `ALL PRIVILEGES` to more specific privileges:

https://github.com/crossplane-contrib/provider-sql/blob/61a16726f9782ddfa117045e87adfa8937e318c0/pkg/controller/mysql/grant/reconciler.go#L394-L403

I guess this would be an exceptional case where revoking the diff only is not really possible? :thinking:

**Comment by luis-alen** [comment]
@Duologic could be also, but it is not my case. I'm not granting `ALL PRIVILEGES`:

```
  For Provider:
    Database:  my-app
    Privileges:
      SELECT
      INSERT
      UPDATE
      DELETE
      CREATE
      DROP
      REFERENCES
      INDEX
      ALTER
      CREATE TEMPORARY TABLES
      LOCK TABLES
      EXECUTE
      CREATE VIEW
      SHOW VIEW
      CREATE ROUTINE
      ALTER ROUTINE
      EVENT
      TRIGGER
```

**Comment by Duologic** [comment]
This seems like a bug to the current implementation, can you create a new issue with the objects that you are applying and describing the steps to reproduce?

**Comment by luis-alen** [comment]
> This seems like a bug to the current implementation, can you create a new issue with the objects that you are applying and describing the steps to reproduce?

@Duologic https://github.com/crossplane-contrib/provider-sql/issues/162

By the way I tested granting `ALL PRIVILEGES` and it works as expected. It only seem to occur with this specific list of privileges I provided above.
