### ISSUE TITLE
make and zz_generated files

### ISSUE THREAD

**Issue by a-dekker** [crossplane-contrib/provider-sql#167]
I am trying to experiment with a small change to the postgres part as someone with some programming experience, but practically zero go programming experience.

After adding some code in line with adding a database or role (but in this case a schema) it starts to complain about a missing methode DeepCopy. It sounds like I need to add some func to `provider-sql/apis/postgresql/v1alpha1/zz_generated.deepcopy.go` for that. I could try that by hand, but as these file should be generated (`Code generated by controller-gen. DO NOT EDIT.` is says), I do not think that is the way to go.

Should a `make` run update these zz_generated files, or is there some separate process/tool (`https://book.kubebuilder.io/reference/controller-gen`?) responsible for that? Or should it be updated by itself and am I perhaps missing something in the code for that? Only `make` and `make reviewable` are mentioned in the readme.

**Comment by Duologic** [comment]
The generated files are created by `make generate`.

I can't reproduce this.
