### ISSUE TITLE
User Managemet CRD's are missing for Postgressql

### ISSUE THREAD

**Issue by nrjsingh167** [crossplane-contrib/provider-sql#175]
### What problem are you facing?

Currently, I am using Crossplane for database provisioning along with user and permission management. When I used PostgreSQL, it missed the user creation/deletion CRDs similar to Mysql/MSSQL 

### How could Crossplane help solve your problem?

If this feature comes soon, then it will help us to make our end-to-end fully managed database solution built on top of crossplane compositions and providers.

**Comment by Bastichou** [comment]
Hi,
I think you can entirely manage this with Roles in PostgreSQL.

[From the manual](https://www.postgresql.org/docs/current/static/sql-createuser.html) "CREATE USER is now an alias for CREATE ROLE. The only difference is that when the command is spelled CREATE USER, LOGIN is assumed by default, whereas NOLOGIN is assumed when the command is spelled CREATE ROLE.
