### ISSUE TITLE
Add the database name into the credentials secret

### ISSUE THREAD

**Issue by drivera-armedia** [crossplane-contrib/provider-sql#190]
### What problem are you facing?

When consuming the generated secret (i.e. endpoint, port, username, password) the Database name is not also provided which can be required in some implementations (notably, Java applications). When consuming the secret, one only knows the name of the secret, but not the name of the `Database` object which caused the secret to be created/populated.

### How could Crossplane help solve your problem?

When generating the secret and populating the `endpoint` and `port` values into the secret, also add a `database` value which contains the name of the underlying database instance.  On that note, if other connectivity-related values such as `schema` (the schema name) or `instance` (the instance name) are sensible to be provided, they should also be provided.

**Comment by Duologic** [comment]
I'd suggest to use a Composition.
