### ISSUE TITLE
Provision MySQL Users

### ISSUE THREAD

**Issue by srueg** [crossplane-contrib/provider-sql#2]
Implement support for provisioning MySQL users. In addition to provisioning databases on SQL servers users should also be supported. We'll start with the implementation for MySQL. Support for PostgreSQL can follow later.

## Implementation Details
* Create a new manged resource `User` in `mysql.sql.crossplane.io/v1alpha1`
* Implement a new `user` reconciler in the `pkg/controller/mysql/user` package
* Provision a user based on the CRD
  * The external name of the managed resource should be used as the user name
  * A password should be generated
  * The complete [ConnectionDetails](https://pkg.go.dev/github.com/crossplane/crossplane-runtime@v0.11.0/pkg/reconciler/managed#ConnectionDetails) should be returned

## Not in Scope
* User TLS options
* User password expire options
* User resource options
* User GRANTs (see #3)

## To be Discussed
I think a more ergonomic (i.e. typed) way to define GRANTs might make sense in the future. For now I'd like to start with a simple approach.

**Comment by srueg** [comment]
@negz please let me know what you think of this approach/proposal.
We'd like to implement a PR once we reach a consensus.

**Comment by negz** [comment]
@srueg Do you suspect it would be a lot more work to implement a distinct grant resource too? I appreciate the desire to keep it simple to begin with, but I suspect we'll want grants to be a distinct resource, which would presumably mean removing them from the user resource (a breaking change).

**Comment by srueg** [comment]
I was also thinking about a distinct resource for GRANTs. I guess it would make the implementation even simpler because it maps better to the concept of SQL. And thinking about it again I like this approach better, using Compositions we can still compose together DBs, users and GRANTs 👍 
I'll change this issue to only implement the user part and open a new one for the GRANTs.
