### ISSUE TITLE
Feature to install PG Extensions

### ISSUE THREAD

**Issue by linuxbsdfreak** [crossplane-contrib/provider-sql#24]
### What problem are you facing?
Feature to install PG extensions as part of creating DB would be a nice
https://www.postgresql.org/docs/9.1/sql-createextension.html
https://www.highgo.ca/2019/07/22/how-to-add-extensions-to-pg-on-ubuntu/

### How could Crossplane help solve your problem?
This would help to cover the whole Post setup process after the DB instance is created. Including User and DB creation.

**Comment by linuxbsdfreak** [comment]
@benagricola. Could you provide me inputs on how the provider-sql could be extended to support installing extensions ?

**Comment by benagricola** [comment]
> @benagricola. Could you provide me inputs on how the provider-sql could be extended to support installing extensions ?

AIUI extensions are cluster-wide, so not served well by being added on an existing type (i.e. if we added this as a list of extension names on postgres `Database`, then this would occur for every created DB which would be pointless).

I think we'd need to implement a new type + reconciler for `Extension` which simply creates or deletes the extension. 

We would observe [pg_extension](https://www.postgresql.org/docs/9.1/catalog-pg-extension.html) to work out whether the extension is installed or not, `create` it using [CREATE EXTENSION](https://www.postgresql.org/docs/current/sql-createextension.html) as you outlined and `delete` it using [DROP EXTENSION](https://www.postgresql.org/docs/current/sql-dropextension.html). Updates would be a no-op.

From an arguments perspective I would probably look at supporting `extension_name` and `version` first, and once that works, adding `schema` (which should be as simple as adding the field and `SCHEMA` support in the create query).

**Comment by linuxbsdfreak** [comment]
Thx @benagricola. How difficult would be it to get started  for work on Installing and removing extensions?
