### ISSUE TITLE
Allow custom db name to be passed to postgres client

### ISSUE THREAD

**Issue by benagricola** [crossplane-contrib/provider-sql#34]
### What problem are you facing?
Postgres has some namespaced resources that others have requested as a use-case, for example database extensions (#24).

Right now, all queries are executed against the `postgres` db as that is defaulted by the underlying driver. This can currently be controlled by setting the `PGDATABASE` environment variable via a `ControllerConfig` but this is provider-wide, and doesn't allow us to e.g. install an extension into a newly-created database.

### How could Crossplane help solve your problem?
We should allow the database to be set on an existing `postgresDB` instance (which would cause a modification of the DSN) so that a reconciler can choose to override the database name that queries are executed against. This will allow for further PR's adding support for Extensions, Grants against databases etc.

**Comment by benagricola** [comment]
@negz (cc: @srueg) I've been looking at an implementation of this to enable #24 using something like the following:

```go
// formatDSN sets the DSN that this client will use
// to connect to PostgreSQL.
func (c postgresDB) formatDSN() {
	c.dsn = fmt.Sprintf("postgres://%s:%s@%s:%s/%s",
		c.username,
		c.password,
		c.endpoint,
		c.port,
		c.database)
}
```

Where `formatDSN()` is called in `New()` and with a new `SetDatabase()` method:

```go
// SetDatabase overrides the existing database name,
// and regenerates the stored DSN.
func (c postgresDB) SetDatabase(db string) {
	c.database = db
	c.formatDSN()
}
```

However I noticed that the underlying value of `c.dsn` is not set when calling `formatDSN()`, as the postgres client is using value receivers so working on a copy of `c`, and then discarding it.

I can of course switch these to use pointer receivers (which _appears_ to work) but my (weak) understanding of this is that pointer receivers are not concurrency safe, and I wonder if these were made value receivers deliberately so they're safe in this regard.

My understanding is that we're creating a new DB instance every time we call `Connect()`, so effectively we only use a DB instance for a single resource, and as we reconcile each individual resource serially we _should not_ have any concurrency issues here and I should be OK to switch this to use pointer receivers.

Does this match with everyone else's understanding of the reconcile loop and how we're using the DB client here?

**Comment by srueg** [comment]
Yes, that's also my understanding. Each DB instance is even only used for a single reconcile run and therefore can never be accessed concurrently.
The crossplane-runtime calls `Connect()` on each reconcile run: https://github.com/crossplane/crossplane-runtime/blob/master/pkg/reconciler/managed/reconciler.go#L601
