### ISSUE TITLE
Support SSL connection for MySQL

### ISSUE THREAD

**Issue by qbast** [crossplane-contrib/provider-sql#46]
### What problem are you facing?

It is currently impossible to use crossplane sql provider if a database server forces SSL connections (for example this can be set on Azure) as there is no parameter to enable it

### How could Crossplane help solve your problem?

There is already a pull request ( https://github.com/crossplane-contrib/provider-sql/pull/40 ) open to add ssl mode support for postgresql. Exactly the same approach could be used for Mysql

**Comment by Duologic** [comment]
I believe [v0.5.0](https://github.com/crossplane-contrib/provider-sql/releases/tag/v0.5.0) solves this issue.
