### ISSUE TITLE
What is the security model?

### ISSUE THREAD

**Issue by benlangfeld** [crossplane-contrib/provider-sql#48]
In a multi-tenant cluster where namespaces A and B are accessible by different users, is there anything in this provider to prevent a user of namespace A providing a `connectionSecretRef` to a `Secret` in namespace B, and thus creating itself a database user on a database server it should not have any access to?

**Comment by protosam** [comment]
I think you can use a policy enforcement tool like [jspolicy](https://github.com/loft-sh/jspolicy) or [kyverno](https://github.com/kyverno/kyverno).

**Comment by negz** [comment]
@benlengfeld the resources in this provider (like all Crossplane providers) are actually cluster scoped, so it's not possible to directly create (e.g.) a `Database` in a particular namespace. Crossplane is designed such that we don't really expect folks to use these resources directly. Instead we'd expect the platform team/cluster operators to define some Crossplane Composite Resources (XRs) that are powered by (i.e. composed of) these resources.

Under this model the connection secret of the `Database` actually becomes sort of an intermediate credentials store. The platform team can specify a fixed namespace for these credentials to be stored in (often `crossplane-system`) and configure how they are surfaced at the abstraction (i.e. Composite Resource Claim) level, where secrets can only be written to the namespace of the claim.

**Comment by benlangfeld** [comment]
@negz Thanks for pointing me in the right direction. I guess the documentation I needed to have read was https://crossplane.io/docs/v1.3/guides/multi-tenant.html.
