### ISSUE TITLE
Ability to create resources in a specific namespace

### ISSUE THREAD

**Issue by vrachok-sc** [crossplane-contrib/provider-sql#58]
### What problem are you facing?

I would like to be able to create resources in a specific namespace.
Now resources are created with scope: cluster.
In my case, a separate database cluster is deployed in each namespace. So I would like to create users and databases only within a specific namespace. 

### How could Crossplane help solve your problem?

I want to use Crossplane to manage users and databases in Percona Extradb Cluster.

**Comment by luis-alen** [comment]
I guess we're facing the same issue @vrachok-sc :D and imho this would be a lovely enhancement.

In our case, db names are not unique across different namespaces.

A workaround would be to add the namespace name to the db name, but:

1. `metadata.name` can't take "_" as you described in https://github.com/crossplane-contrib/provider-sql/issues/59 and using dashes could be problematic

Of course provider-sql uses quotes when referring to such resources, but other apps might not do the same.

[Permitted characters in unquoted identifiers](https://dev.mysql.com/doc/refman/5.7/en/identifiers.html)

> an identifier may be quoted or unquoted. If an identifier **contains special characters** or is a reserved word, **you must quote it whenever you refer to it.**

> Permitted characters in unquoted identifiers:
  ASCII: [0-9,a-z,A-Z$_] **(basic Latin letters, digits 0-9, dollar, underscore)**

To clarify with a simple example:

```
MariaDB [(none)]> create database luis-test;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-test' at line 1

MariaDB [(none)]> create database `luis-test`;
Query OK, 1 row affected (0.000 sec)
```

2. if we want to manage such existing databases with provider-sql, we must come up with some database renaming (that could very likely involve data migration) and change our applications to reflect the new db names. Unless we do so, we can't manage those databases with provider-sql, only its users and grants.

**Comment by Duologic** [comment]
I believe this is due to the architectural decisions at the Crossplane level, not specific to a single provider.

I'd suggest looking into Compositions and CompositeRersourceDefinitions which allow you to create namespaced resources. With the [External Name annotation](https://crossplane.io/docs/v1.7/concepts/managed-resources.html#external-name) you can configure the name of a database instead of using the k8s object metadata.name.
