### ISSUE TITLE
Prevent Database Deletion?

### ISSUE THREAD

**Issue by MattMencel** [crossplane-contrib/provider-sql#78]
Is it possible to prevent the deletion of the database once it's created by the provider? If I delete the `databases.mysql.sql.crossplane.io` resource, the database is deleted from MySQL. This is fine if I'm just experimenting, but I don't trust humans (me) or automation to not mess it up in some way on a database in production.

Some way to lock it so even if I delete the resource the database doesn't get removed? Otherwise, I can just create the database outside of Crossplane.

**Comment by luis-alen** [comment]
@MattMencel what you're looking for is `deletionPolicy: Orphan`

https://github.com/crossplane-contrib/provider-sql/blob/master/package/crds/mysql.sql.crossplane.io_databases.yaml#L47-L51
