### ISSUE TITLE
Add RDS CA to Docker image

### ISSUE THREAD

**Issue by petteja** [crossplane-contrib/provider-sql#94]
### What problem are you facing?
One popular use case is to use provider-sql with Amazon RDS. The latest version introduced `verify-full` as default sslMode, which requires that provider-sql needs to trust the RDS CA to be able to connect. Without trust it will return `x509: certificate signed by unknown authority` when trying to connect.

### How could Crossplane help solve your problem?
I think that the RDS CA should be added to the Docker image, so that it works out of the box for RDS.

**Comment by Duologic** [comment]
Perhaps we can pass along the root certs to the ProviderConfig as a Secret/ConfigMap reference? This way we can make the feature available to anyone using different root certs.

WDYT?

**Comment by petteja** [comment]
Yes, that is also an option. More config for users, but as you say that makes it easy to support other CAs. Or is this something that would fit better for ControllerConfig?

**Comment by petteja** [comment]
I think that RDS should work out the box without additional config as it is a fairly common use case. Support for custom CAs through config could be implemented later if anyone requests it?

**Comment by Duologic** [comment]
I'd rather not see arbitrary (common or not) embedded in the provider, it puts a maintenance burden on the provider as we'd have to follow up with any changes on that end upstream.

**Comment by Duologic** [comment]
As said, I don't think we should include CSP level certificates.

Would this PR cover the problem as well? https://github.com/crossplane-contrib/provider-sql/pull/184
