### ISSUE TITLE
Support Azure Username Format

### ISSUE THREAD

**Issue by clementblaise** [crossplane-contrib/provider-sql#95]
### What problem are you facing?

Azure Postgres instance connection string use a username formatted as <role_name>@<database_name>. This make it impossible to use the connection string directly since username returned is only the role name

### How could Crossplane help solve your problem?

The `role.postgresql.sql.crossplane.io` resource could add an optional field for a user suffix and be use to template the correct connection string username

**Comment by Duologic** [comment]
No response, closing this.
