### ISSUE TITLE
When removing multiple manifests for Grant at the same time, only 1 gets actioned

### ISSUE THREAD

**Issue by alexbowers** [crossplane-contrib/provider-sql#96]
### What happened?
I had 3 different `SELECT` grants for different databases for the same user in MySQL.

In MySQL they showed up as:

```
GRANT SELECT ON `db1`.* TO 'abowers'@'%'
GRANT SELECT ON `db2`.* TO 'abowers'@'%'
GRANT SELECT ON `db3`.* TO 'abowers'@'%'
```

These were setup the following way:

```
apiVersion: 'mysql.sql.crossplane.io/v1alpha1',
kind: 'Grant',
metadata: {
    name: `abowers-grant-db1`,
},
spec: {
    forProvider: {
        privileges: [
            'ALL'
        ],
        userRef: {
            name: 'abowers'
        },
        database: 'db1',
    }
},
```

etc.

These were all created at the same time, and they worked.

When I removed the manifests completely from Kubernetes at the same time (Using Pulumi / Terraform), the 3 manifests were removed successfully, and I cannot see them in the kubectl output; however, looking at the database, only 1 of the 3 gets removed, the other 2 still has the permissions there.

### What environment did it happen in?
Crossplane version: v0.4.1

**Comment by Duologic** [comment]
Closing as stale, the grant code has been through several iterations since this issue was opened. Please re-open and update if this is still valid.
