### ISSUE TITLE
password with special chars isn't working properly

### ISSUE THREAD

**Issue by cskinfill** [crossplane-contrib/provider-sql#98]
### What happened?
Testing crossplane provider-sql with a mysql database wasn't able to authenticate to the database.  The password contained special chars (specifically `^`, and `!`).  Using an account with special characters worked correctly.

### How can we reproduce it?
I was able to reproduce this each time I used credentials with special characters.

### What environment did it happen in?
* Crossplane version: `v1.8.1`
* provider-sql version: `v0.5.0`
* AWS EKS
* Kubernetes version `v1.21.12-eks-a64ea69`

This line https://github.com/crossplane-contrib/provider-sql/blob/master/pkg/clients/mysql/mysql.go#L54 encodes the username and password when the DSN is created.  However, according to the README for the go mysql driver, the password does NOT need to be escaped (see https://github.com/go-sql-driver/mysql#password).

**Comment by rafaelcalleja** [comment]
I'm having the same problem with password having `#` special char.
